/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhop1;

import javax.swing.JOptionPane;

/**
 *
 * @author Ryan Guiwison
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        grupoDC.add(rbDCsim);
        grupoDC.add(rbdcNAO);
        grupoDC.add(rbdcnsr);
        grupoDG.add(rbdgSIM);
        grupoDG.add(rbdgNAO);
        grupoDG.add(rbdgnsr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        grupoDC = new javax.swing.ButtonGroup();
        grupoDG = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfreferencia = new javax.swing.JTextField();
        lblreferencia = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfrua = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        tfcep = new javax.swing.JTextField();
        lblcep = new javax.swing.JLabel();
        tfcidade = new javax.swing.JTextField();
        lblcidade = new javax.swing.JLabel();
        tfnumero = new javax.swing.JTextField();
        jblnumero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfcelular = new javax.swing.JTextField();
        lblcelular = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lbltelefone = new javax.swing.JLabel();
        tftelefone = new javax.swing.JTextField();
        lbltelefone2 = new javax.swing.JLabel();
        tftelefone2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tfidade = new javax.swing.JTextField();
        lblidade = new javax.swing.JLabel();
        tfnacionalidade = new javax.swing.JTextField();
        lblnacionalidade = new javax.swing.JLabel();
        lblrg = new javax.swing.JLabel();
        tfrg = new javax.swing.JTextField();
        lblSUS = new javax.swing.JLabel();
        tfSUS = new javax.swing.JTextField();
        lblnome = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        lblcpf = new javax.swing.JLabel();
        tfcpf = new javax.swing.JTextField();
        lblsexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        lblestadocivil = new javax.swing.JLabel();
        cbestadocivil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbgenero = new javax.swing.JComboBox<>();
        jp3 = new javax.swing.JPanel();
        cbcolesterol = new javax.swing.JCheckBox();
        cbnenhuma = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();
        lblDoenças = new javax.swing.JLabel();
        cbdiabetes = new javax.swing.JCheckBox();
        cbhipertensao = new javax.swing.JCheckBox();
        lblDoenças1 = new javax.swing.JLabel();
        lblDoenças2 = new javax.swing.JLabel();
        rbDCsim = new javax.swing.JRadioButton();
        rbdcNAO = new javax.swing.JRadioButton();
        rbdcnsr = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbdgSIM = new javax.swing.JRadioButton();
        rbdgNAO = new javax.swing.JRadioButton();
        rbdgnsr = new javax.swing.JRadioButton();
        cbobesidade = new javax.swing.JCheckBox();
        lblobservações = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAobs = new javax.swing.JTextArea();
        btncancelar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSobre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btncancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblreferencia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblreferencia.setText("Referência");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Bairro");

        lblRua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRua.setText("Rua");

        lblcep.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcep.setText("CEP");

        lblcidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcidade.setText("Cidade");

        jblnumero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jblnumero.setText("Nº");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblreferencia)
                    .addComponent(jLabel9)
                    .addComponent(tfrua, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcep)
                    .addComponent(tfcep, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(tfcidade)
                    .addComponent(lblcidade)
                    .addComponent(jblnumero)
                    .addComponent(tfnumero))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblreferencia)
                        .addGap(3, 3, 3)
                        .addComponent(tfreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jblnumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcep)
                        .addGap(3, 3, 3)
                        .addComponent(tfcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        lblcelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcelular.setText("Celular");

        lblemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblemail.setText("E-mail");

        lbltelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone.setText("Telefone");

        lbltelefone2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone2.setText("Telefone 2 (opcional)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcelular)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltelefone2)
                    .addComponent(tftelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefone))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(lbltelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcelular)
                    .addComponent(lbltelefone2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        tfidade.setToolTipText("");
        tfidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidadeActionPerformed(evt);
            }
        });

        lblidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblidade.setText("Idade");

        lblnacionalidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnacionalidade.setText("Nacionalidade ");

        lblrg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblrg.setText("RG");

        lblSUS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSUS.setText("SUS");

        lblnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnome.setText("Nome");

        lblcpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcpf.setText("CPF");

        lblsexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblsexo.setText("Sexo");

        cbSexo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cbSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblestadocivil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblestadocivil.setText("Estado civil");

        cbestadocivil.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado(a)", "Solteiro(a)", "Divorciado(a)", "Viúvo(a)" }));
        cbestadocivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Gênero");

        cbgenero.setEditable(true);
        cbgenero.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cisgênero", "Transgênero", "Não-binário" }));
        cbgenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnome)
                    .addComponent(lblcpf)
                    .addComponent(tfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblsexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblestadocivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrg)
                                    .addComponent(tfrg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSUS)
                                    .addComponent(tfSUS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidade)
                            .addComponent(tfidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnacionalidade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(lblrg)
                    .addComponent(lblnacionalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcpf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblidade)
                        .addComponent(lblSUS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsexo)
                    .addComponent(lblestadocivil)
                    .addComponent(cbestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jp3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cbcolesterol.setText("Colesterol alto (dislipidemia)");

        cbnenhuma.setText("Nenhuma das citadas acima.");
        cbnenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnenhumaActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblDoenças.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDoenças.setText("Você possui alguma das doenças abaixo?");

        cbdiabetes.setText("Diabetes");

        cbhipertensao.setText("Hipertensão");
        cbhipertensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhipertensaoActionPerformed(evt);
            }
        });

        lblDoenças1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblDoenças2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDoenças2.setText("Histórico familiar de doenças cardiovasculáres?");

        rbDCsim.setText("Sim");

        rbdcNAO.setText("Não");

        rbdcnsr.setText("Não sabe responder");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Histórico familiar de doenças genéticas?");

        rbdgSIM.setText("Sim");

        rbdgNAO.setText("Não");

        rbdgnsr.setText("Não sabe responder");
        rbdgnsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdgnsrActionPerformed(evt);
            }
        });

        cbobesidade.setText("Obesidade");
        cbobesidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbobesidadeActionPerformed(evt);
            }
        });

        lblobservações.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblobservações.setText("Observações ");

        txtAobs.setColumns(20);
        txtAobs.setRows(5);
        txtAobs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.setViewportView(txtAobs);

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDoenças)
                                    .addComponent(btnRegistrar)
                                    .addComponent(cbnenhuma)
                                    .addGroup(jp3Layout.createSequentialGroup()
                                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbobesidade)
                                            .addComponent(cbdiabetes))
                                        .addGap(18, 18, 18)
                                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbhipertensao)
                                            .addComponent(cbcolesterol))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDoenças1))
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(rbdgSIM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbdgNAO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbdgnsr))
                            .addComponent(jLabel3)
                            .addComponent(lblDoenças2)
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rbDCsim)
                                .addGap(12, 12, 12)
                                .addComponent(rbdcNAO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbdcnsr))
                            .addComponent(lblobservações)))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoenças)
                    .addComponent(lblDoenças1))
                .addGap(12, 12, 12)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbhipertensao)
                    .addComponent(cbdiabetes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbobesidade)
                    .addComponent(cbcolesterol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbnenhuma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbdgSIM)
                    .addComponent(rbdgNAO)
                    .addComponent(rbdgnsr))
                .addGap(18, 18, 18)
                .addComponent(lblDoenças2)
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDCsim)
                    .addComponent(rbdcNAO)
                    .addComponent(rbdcnsr))
                .addGap(18, 18, 18)
                .addComponent(lblobservações)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        btncancelar.setBackground(new java.awt.Color(204, 204, 204));
        btncancelar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/x.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setBorder(null);
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirmar.png"))); // NOI18N
        btnsalvar.setText("SALVAR");
        btnsalvar.setBorder(null);
        btnsalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnSobre.setBackground(java.awt.SystemColor.control);
        btnSobre.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSobre.setForeground(new java.awt.Color(51, 51, 51));
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre.png"))); // NOI18N
        btnSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/finalogo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btncancelar1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btncancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        btncancelar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btncancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(672, 672, 672)
                        .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btncancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(160, 10, 1030, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbnenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnenhumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnenhumaActionPerformed

    private void cbhipertensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhipertensaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbhipertensaoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (cbcolesterol.isSelected()){
            JOptionPane.showMessageDialog(null,"Registrado! Você possui:  " + cbcolesterol.getText() );
        }
    if (cbdiabetes.isSelected()){
            JOptionPane.showMessageDialog(null, "Registrado! Você possui:  " +cbdiabetes.getText() );
        }
    if (cbhipertensao.isSelected()){
            JOptionPane.showMessageDialog(null,"Registrado! Você possui:  " + cbhipertensao.getText() );
        }
    if (cbobesidade.isSelected()){
            JOptionPane.showMessageDialog(null,"Registrado! Você possui:  " + cbobesidade.getText() );
        }
    if (cbnenhuma.isSelected()){
            JOptionPane.showMessageDialog(null,"Registrado! Você não possui nenhuma das doenças listadas." );
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        JOptionPane.showMessageDialog(null, "O SUNI é um programa desenvolvido para auxiliar e facilitar o dia a dia dos orgãos públicos de saúde.\nNo momento atual, você se encontra na tela de cadastro de pacientes.");
    }//GEN-LAST:event_btnSobreActionPerformed

    private void tfidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidadeActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        JOptionPane.showMessageDialog(null, "Informações salvas. Cadastro do paciente realizado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        JOptionPane.showMessageDialog(null, "O cadastro do paciente foi interrompido.");
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void rbdgnsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdgnsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdgnsrActionPerformed

    private void cbobesidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbobesidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbobesidadeActionPerformed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        JOptionPane.showMessageDialog(null,"Todos os campos foram limpos!");
        tfnome.setText("");
        tfrg.setText("");
        tfnacionalidade.setText("");
        tfcpf.setText("");
        tfSUS.setText("");
        tfidade.setText("");
        tfemail.setText("");
        tfcelular.setText("");
        tftelefone.setText("");
        tftelefone2.setText("");
        tfcep.setText("");
        tfrua.setText("");
        tfnumero.setText("");
        tfbairro.setText("");
        tfcidade.setText("");
        tfreferencia.setText("");
        txtAobs.setText("");
        cbSexo.setSelectedIndex(0);
        cbestadocivil.setSelectedIndex(0);
        cbgenero.setSelectedIndex(0);
        grupoDC.clearSelection();
        grupoDG.clearSelection();
        cbdiabetes.setSelected(false);
        cbhipertensao.setSelected(false);
        cbobesidade.setSelected(false);
        cbcolesterol.setSelected(false);
        cbnenhuma.setSelected(false);
        
    }//GEN-LAST:event_btncancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSobre;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JCheckBox cbcolesterol;
    private javax.swing.JCheckBox cbdiabetes;
    private javax.swing.JComboBox<String> cbestadocivil;
    private javax.swing.JComboBox<String> cbgenero;
    private javax.swing.JCheckBox cbhipertensao;
    private javax.swing.JCheckBox cbnenhuma;
    private javax.swing.JCheckBox cbobesidade;
    private javax.swing.ButtonGroup grupoDC;
    private javax.swing.ButtonGroup grupoDG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblnumero;
    private javax.swing.JPanel jp3;
    private javax.swing.JLabel lblDoenças;
    private javax.swing.JLabel lblDoenças1;
    private javax.swing.JLabel lblDoenças2;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSUS;
    private javax.swing.JLabel lblcelular;
    private javax.swing.JLabel lblcep;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblestadocivil;
    private javax.swing.JLabel lblidade;
    private javax.swing.JLabel lblnacionalidade;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblobservações;
    private javax.swing.JLabel lblreferencia;
    private javax.swing.JLabel lblrg;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lbltelefone2;
    private javax.swing.JRadioButton rbDCsim;
    private javax.swing.JRadioButton rbdcNAO;
    private javax.swing.JRadioButton rbdcnsr;
    private javax.swing.JRadioButton rbdgNAO;
    private javax.swing.JRadioButton rbdgSIM;
    private javax.swing.JRadioButton rbdgnsr;
    private javax.swing.JTextField tfSUS;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfcelular;
    private javax.swing.JTextField tfcep;
    private javax.swing.JTextField tfcidade;
    private javax.swing.JTextField tfcpf;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfidade;
    private javax.swing.JTextField tfnacionalidade;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfnumero;
    private javax.swing.JTextField tfreferencia;
    private javax.swing.JTextField tfrg;
    private javax.swing.JTextField tfrua;
    private javax.swing.JTextField tftelefone;
    private javax.swing.JTextField tftelefone2;
    private javax.swing.JTextArea txtAobs;
    // End of variables declaration//GEN-END:variables
}
